site_name: Open Science Knowledge Base
site_description: An annotated collection of open science resources
docs_dir: 'content'
theme:
  name: 'material'
  custom_dir: 'content/_theme'
extra_css:
  - '_styles/extra.css'
extra_javascript:
  - '_scripts/credits.js'
copyright: 'Built by scientists like you.'
markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
repo_name: 'felixhenninger/open-science-knowledge-base'
repo_url: 'https://github.com/felixhenninger/open-science-knowledge-base'
edit_uri: 'edit/master/content/'
