site_name: Open Science Knowledge Base
site_description: An annotated collection of open science resources
site_url: https://how-to-open.science
docs_dir: 'content'
theme:
  name: 'material'
  custom_dir: 'content/_theme'
extra_css:
  - '_styles/extra.css'
extra_javascript:
  - '_scripts/credits.js'
copyright: 'Built by scientists like you.'
markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.tilde
repo_name: 'felixhenninger/open-science-knowledge-base'
repo_url: 'https://github.com/felixhenninger/open-science-knowledge-base'
edit_uri: 'edit/master/content/'
strict: true
nav:
  - Overview: 'index.md'
  - Changing scientific practice: 'change/educate/first-steps.md'
    - What's the matter?:
      - Introduction to reproducible science: 'change/educate/literature.md'
      - Where to ask questions: 'change/educate/ask.md'
    - First steps: 'change/get_started.md'
    - Open Science community: 'change/community/community.md'
      - Online Community: 'change/community/online_community.md'
      - Offline Community: 'change/community/offline_community.md'
      - Ongoing collaborative efforts: 'change/community/collaboration.md'
    - Recognizing open science:
      - Open Science Badges: 'change/recognize/badges.md'
    - Changing institutions:
      - Hiring practices: 'change/institutions/hiring.md'
      - Lab Transition: 'change/institutions/lab.md'
      - Local Open Science Initiative: 'change/institutions/uni.md'
    - Teaching resources: 'change/teaching/resources.md'
    - Contribute to this resource: 'change/community/contribute.md'
  - Theorizing:
    - Knowledge synthesis: 'theorize/synthesis.md'
  - Planning research:
    - Preregistration:
      - Motivation: 'plan/preregistration/why.md'
      - Methods: 'plan/preregistration/how.md'
      - Scope: 'plan/preregistration/scope.md'
      - Binding character: 'plan/preregistration/change.md'
      - Teaching: 'plan/preregistration/teaching.md'
    - Registered reports: 'plan/registered-reports.md'
  - Analysis:
    - Reproducibility: 'analyze/reproducibility.md'
    - Avoiding mistakes: 'analyze/mistakes.md'
  - Sharing:
    - Documentation:
      - Open Methodology: 'share/open-methodology.md'
    - Open Data:
      - Definition: 'share/open-data/definition.md'
      - Best practices: 'share/open-data/best-practices.md'
      - Repositories: 'share/open-data/repositories.md'
      - Ensuring privacy: 'share/open-data/privacy.md'
    - Licenses: 'share/licenses.md'
  - Dissemination:
    - Preprints:
      - Motivation: 'disseminate/preprints/motivation.md'
      - Preprint servers: 'disseminate/preprints/servers.md'
      - Engaging with preprints: 'disseminate/preprints/engage.md'
    - Articles:
      - Sharing papers: 'disseminate/articles/sharing.md'
    - Peer review: 'disseminate/articles/review.md'
    - Registered reports: 'plan/registered-reports.md'
